services:
  dev-qrmint-web:
    build: ${FRONT_PATH}
    hostname: ${FRONT_NAME}
    container_name: ${FRONT_NAME}
    restart: "always"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    volumes:
      - ${FRONT_PATH}/nginx/logs:/var/log/nginx
    expose:
      - ${FRONT_PORT}
    networks:
      - qrmint
    labels:
      - "traefik.docker.network=qrmint-proxy"
      - "traefik.enable=true"
      - "traefik.http.routers.${FRONT_NAME}.rule=Host(`$FRONT_HOSTNAME`)"
      - "traefik.http.routers.${FRONT_NAME}.entrypoints=web,websecure"
      - "traefik.http.routers.${FRONT_NAME}.tls.certresolver=default"
networks:
  qrmint:
    driver: bridge
    name: qrmint-proxy
